objects:
  role:
    credential:
      description: An Ansible Role to create credentials in EDA controller.
      name: credential
      version_added: null
    decision_environment:
      description: An Ansible Role to create decision environments in EDA controller.
      name: decision_environment
      version_added: null
    dispatch:
      description: An Ansible Role to call other roles to create objects on Ansible
        eda.
      name: dispatch
      version_added: null
    project:
      description: An Ansible Role to create projects in EDA controller.
      name: project
      version_added: null
    project_sync:
      description: An Ansible Role to sync projects in EDA controller.
      name: project_sync
      version_added: null
    rulebook_activation:
      description: An Ansible Role to create rulebook activations in EDA controller.
      name: rulebook_activation
      version_added: null
    user:
      description: An Ansible Role to create users in EDA controller.
      name: user
      version_added: null
    controller_token:
      description: An Ansible Role to create user tokens in EDA controller.
      name: controller_token
      version_added: null
  netconf: {}
  shell: {}
  strategy: {}
  test: {}
  vars: {}
version: 1.1.0
