objects:
  role:
    credential:
      description: An Ansible Role to create credentials in EDA controller.
      name: credential
      version_added: null
    decision_environment:
      description: An Ansible Role to create decision environments in EDA controller.
      name: decision_environment
      version_added: null
    dispatch:
      description: An Ansible Role to call other roles to create objects on Ansible
        eda.
      name: dispatch
      version_added: null
    project:
      description: An Ansible Role to create projects in EDA controller.
      name: project
      version_added: null
    project_sync:
      description: An Ansible Role to sync projects in EDA controller.
      name: project_sync
      version_added: null
    rulebook_activation:
      description: An Ansible Role to create rulebook activations in EDA controller.
      name: rulebook_activation
      version_added: null
    user:
      description: An Ansible Role to create users in EDA controller.
      name: user
      version_added: null
    user_token:
      description: An Ansible Role to create user tokens in EDA controller.
      name: user_token
      version_added: null
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  filter: {}
  httpapi: {}
  inventory: {}
  lookup:
    eda_api:
      description: Search the API for objects
      name: eda_api
      version_added: null
  module:
    credential:
      description: Manage a Credential in EDA Controller
      name: credential
      namespace: ''
      version_added: null
    decision_environment:
      description: Manage a Decision Environment in EDA Controller
      name: decision_environment
      namespace: ''
      version_added: null
    project:
      description: Manage a project in EDA Controller
      name: project
      namespace: ''
      version_added: null
    project_sync:
      description: Sync a project in EDA Controller
      name: project_sync
      namespace: ''
      version_added: null
    rulebook_activation:
      description: Manage a rulebook_activation in EDA Controller
      name: rulebook_activation
      namespace: ''
      version_added: null
    user:
      description: Manage a user in EDA Controller
      name: user
      namespace: ''
      version_added: null
    user_token:
      description: Manage the user tokens of the current user in EDA Controller
      name: user_token
      namespace: ''
      version_added: null
  netconf: {}
  shell: {}
  strategy: {}
  test: {}
  vars: {}
version: 1.1.0
